import defaultBreakIdeas from './defaultBreakIdeas.js'
import defaultMicrobreakIdeas from './defaultMicrobreakIdeas.js'
import { insideFlatpak, insideWindowsStore, insideSnap, insideWindowsPortable } from './utils.js'

export default {
  microbreakDuration: 20000,
  microbreakInterval: 600000,
  breakDuration: 300000,
  breakInterval: 2,
  breakNotification: true,
  microbreakNotification: true,
  breakNotificationInterval: 30000,
  microbreakNotificationInterval: 10000,
  microbreak: true,
  break: true,
  microbreakStrictMode: false,
  breakStrictMode: false,
  morningHour: 6,
  microbreakPostpone: true,
  breakPostpone: true,
  microbreakPostponeTime: 120000,
  // Long-break postpone preset: +10 min (RSIGuard-style). Upstream default is
  // 300000 (+5 min); not exposed in the preferences UI, so changed here.
  breakPostponeTime: 600000,
  microbreakPostponesLimit: 1,
  microbreakPostponableDurationPercent: 30,
  breakPostponesLimit: 1,
  breakPostponableDurationPercent: 30,
  mainColor: '#478484',
  miniBreakColor: '#478484',
  transparentMode: false,
  blurredBackground: false,
  opacity: 0.9,
  longBreakAudio: 'crystal-glass',
  miniBreakAudio: 'crystal-glass',
  volume: 1,
  fullscreen: false,
  ideas: true,
  naturalBreaks: true,
  naturalBreaksInactivityResetTime: 300000,
  // Activity-based (RSIGuard-style) break trigger. Off by default; requires the
  // optional uiohook-napi global input hook and, on macOS, Input Monitoring /
  // Accessibility permission granted to Stretchly.
  activityTrigger: false,
  activityThreshold: 6000,
  activityKeyWeight: 1,
  activityClickWeight: 2,
  activityMoveWeight: 1,
  activityIdleResetTime: 30000,
  activityDecayPerSecond: 0.1,
  allScreens: true,
  useIdeasFromSettings: false,
  language: 'en',
  notifyNewVersion: true,
  isFirstRun: true,
  posLatitude: 0.0,
  posLongitude: 0.0,
  useMonochromeTrayIcon: false,
  trayIconThemeSource: 'system',
  silentNotifications: false,
  monitorDnd: true,
  miniBreakStartSound: 'silence',
  longBreakStartSound: 'silence',
  themeSource: 'system',
  endBreakShortcut: 'CmdOrCtrl+X',
  breakWindowWidth: 0.85,
  breakWindowHeight: 0.85,
  checkNewVersion: true,
  breakIdeas: defaultBreakIdeas,
  microbreakIdeas: defaultMicrobreakIdeas,
  showBreaksAsRegularWindows: false,
  appExclusions: [],
  appExclusionsCheckInterval: 1000,
  pauseForSuspendOrLock: true,
  pauseBreaksToggleShortcut: '',
  pauseBreaksFor30MinutesShortcut: '',
  pauseBreaksFor1HourShortcut: '',
  pauseBreaksFor2HoursShortcut: '',
  pauseBreaksFor5HoursShortcut: '',
  pauseBreaksUntilMorningShortcut: '',
  screen: 'primary',
  breakContentScreen: 'all',
  trayIconStyle: 'default',
  currentTimeInBreaks: false,
  showTrayIcon: true,
  skipToNextScheduledBreakShortcut: '',
  skipToNextMiniBreakShortcut: '',
  skipToNextLongBreakShortcut: '',
  resetBreaksShortcut: '',
  showTrayMenuInStrictMode: false,
  customPreferencesMessage: '',
  disableAppUpdateFeatures: insideFlatpak() || insideWindowsStore() || insideSnap() || insideWindowsPortable(),
  hidePreferencesFileLocation: false,
  hideStrictModePreferences: false,
  miniBreakManualFinish: false,
  longBreakManualFinish: false,
  breakHealthMode: false,
  openAtLogin: false,
  _migratedOpenAtLogin: false
}
